on:
  push:
    branches: [master]
    paths-ignore: 
      - "**.md" 
  pull_request:
    paths-ignore: 
      - "**.md" 

name: Code Coverage

jobs:
  coverage:
    # Don't run coverage on merge queue CI to avoid duplicating codecov reports
    if: github.event_name != 'merge_group'
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run llvm-cov
        run: cargo llvm-cov --all-features --doctests --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
